### ISSUE TITLE
Review 'single cell isolation'/'isolation of cell population' branch

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#1248]
@rachadele asked for advice on the most appropriate term to represent an enrichment cell culture step. Paper says:
"Microglia were separated and removed by an initial adhesion step in which the total cell fraction was cultured for 24 hours in non-coated flasks."

I'd suggest using OBI:0000512 'isolation of cell population' already in HCAO (see image attached). The OBI definition is "a process in which a population of cells with certain characteristics is isolated from a larger population", which is fitting.

If a more specific term is desired to detail the isolation mechanism, we could create an EFO term, child of OBI:0000512 'isolation of cell population', labelled 'cell culture enrichment by differential adhesion' perhaps (as per another paper I found, PMID:29546701). If so, Rachel could you please provide the PMID of the original text? (And Rachel's ORCID is https://orcid.org/0000-0002-7431-4139).

Let me know which option you prefer.
Thanks,
Paola

![Screen Shot 2021-09-10 at 12 27 11](https://user-images.githubusercontent.com/4982516/132840260-d05a2834-5358-4248-8646-4a5a73a73332.png)

**Comment by paolaroncaglia** [comment]
Note to self:
In EFO, OBI:0000512 'isolation of cell population' has the additional EFO rdfs:label '_single_ cell isolation' with EFO def "A method to separate a single cell suspension into _individual_ cells in order to allow individual cell barcoding.". I think it'd be more appropriate to have the main term not refer to isolation of individual cells (so sticking to OBI's label and definition), and create a child term for 'single cell isolation' instead (with EFO label and def as above). @anjaf or others, any opinions please? 
Thanks.
Paola

**Comment by paolaroncaglia** [comment]
@rachadele
If 'isolation of cell population' is too broad for HCA's needs, instead of creating a new EFO term for 'cell culture enrichment by differential adhesion', we could easily import another OBI term into HCAO - it's also a child of 'isolation of cell population':
OBI:0000540 isolation of adherent cells "a material separation process in which cells that stick to the container in which they are grown as a cell culture are separated from those in the liquid component of the culture. The output of this process are adherent cells.". Based on the text sentence you provided, it seems fitting, but please confirm.
Thanks,
Paola

**Comment by anjaf** [comment]
> In EFO, OBI:0000512 'isolation of cell population' has the additional EFO rdfs:label '_single_ cell isolation' with EFO def "A method to separate a single cell suspension into _individual_ cells in order to allow individual cell barcoding.". I think it'd be more appropriate to have the main term not refer to isolation of individual cells (so sticking to OBI's label and definition), and create a child term for 'single cell isolation' instead (with EFO label and def as above). @anjaf or others, any opinions please?

Yes, separate terms make sense. We had a discussion previously with Simon/Ola about this but never reached a consensus. I agree that we were mixing concepts here. One is the process of picking a desired set of cells out of a larger pool and the other refers to the encapsulation or separation of individual cells (the "single cell isolation"). 

But I'm thinking that Fluidigm C1 and the droplet term only belong in the latter category not the first. So perhaps make them sister terms instead of child terms?

**Comment by paolaroncaglia** [comment]
Hi @anjaf ,
Thanks for your reply. I agree that the 'single cell isolation'/'isolation of cell population' branch could be improved. One time-effective way of doing that would be a screen-sharing meeting where I edit EFO based on input from you and anyone else interested in distinguishing between isolation of a cell population vs. single cells. The branch is small, so the meeting could be short. And for anyone unable to attend, we could share the edits before committing them to public EFO, if necessary. Things to consider:
- [ ] The aim is to improve the branch and its existing members, not to drastically change terms' parentage, i.e. we don't want to break AE/GXA/SCA/HCA pipelines
- [ ] Who attends: comments welcome, but let's not get blocked - even if it's just 2 of us, we can share/discuss changes later
- [ ] When: I can suggest a couple of time slots, offline once the above is agreed
- [ ] 'droplet-based cell isolation' needs a definition
- [ ] Some terms need references
- [ ] Remember to check if OBI has existing, appropriate terms that we could import
- [ ] Share edits before committing if people can't attend.   

@ngeorgeebi @sfexova @pnejad
Tagging you too here: no immediate action is required, but if you have any thoughts on the above, please feel free to comment.

Thanks,
Paola

**Comment by rachadele** [comment]
@paolaroncaglia I think the OBI:0000540 'isolation of adherent cells' definition sounds good. The total enrichment protocol for this dataset was:

"Microglia were separated and removed by an initial adhesion step in which the total cell fraction was cultured for 24 hours in non-coated flasks. The floating cell fraction was subjected to immunomagnetic bead selection with the A2B5 antibody (IgM), which recognizes gangliosides to remove a progenitor cell pool that comprises 3 to 5% of white matter cells. "

So I believe for this dataset, the single cell isolation step came after cell culture. I hope that helps!

**Comment by paolaroncaglia** [comment]
Hi @rachadele ,
Thanks. We will import OBI:0000540 'isolation of adherent cells' then. I'll comment here when that's done.

**Comment by paolaroncaglia** [comment]
Hi again @rachadele (cc @pnejad),
For you to be able to use a newly imported OBI term, would it work if the term were simply added to the HCA EFO slim?
Or would you strictly need it to be imported into HCAO?
We can do both, but in the latter case we'll need to modify the HCAO release pipeline a little. Asking now so Zoë can arrange any necessary task. Thanks!

**Comment by rachadele** [comment]
I'm not sure, @pnejad would probably know !

**Comment by pnejad** [comment]
@paolaroncaglia I'm actually not sure how HCAO vs HCA EFO slim works. I think someone on the EBI ingest/wrangling team may be better suited to answer this question. 

Perhaps @aaclan-ebi or @ESapenaVentura ?

**Comment by ESapenaVentura** [comment]
@pnejad for our purposes, functionally it makes no distinction

As a summary (@paolaroncaglia feel free to correct me if I'm incorrect in this), the difference is:

- Importing as part of HCA's EFO slim: Term is imported to the "trimmed down" version of EFO in the HCAO (Example: https://ontology.staging.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0400110)
- Importing into HCAO: Term needs to be imported under the OBI hierarchy, which implies modifying the OBI owl

Unless we want the specific OBI hierarchy for the term (Which may be difficult because we want the proceses to be under an EFO ontology), importing it under the HCA EFO slim I think is fine!

**Comment by paolaroncaglia** [comment]
@ESapenaVentura thanks for confirming. Importing in the HCA EFO slim will also be quicker and simpler.
@rachadele @pnejad I'll comment again here when done.

**Comment by paolaroncaglia** [comment]
@rachadele @pnejad 
OBI_0000540 isolation of adherent cells
is now in EFO and will be in the HCA EFO slim.

**Comment by paolaroncaglia** [comment]
Leaving this ticket open to address https://github.com/EBISPOT/efo/issues/1248#issuecomment-916987799.

**Comment by rachadele** [comment]
Hi @paolaroncaglia, when is the HCAO EFO slim release?

**Comment by paolaroncaglia** [comment]
Hi @rachadele ,

> when is the HCAO EFO slim release?

It's already been done - I checked yesterday and the term OBI_0000540 'isolation of adherent cells' was already in the HCA OLS production instance (see [here](https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000540)). 
The relevant ticket (https://github.com/ebi-ait/hca-ebi-dev-team/issues/444) is in fact now closed. Zoë tags some of you HCA wranglers in those monthly HCAO release tickets, so you can be aware of when we've released HCAO and the EFO slim, and you may then check if your terms are available (or follow up with the ticket assignee if not).
Any question, feel free to ask.

Paola

**Comment by rachadele** [comment]
Thanks Paola!
Unfortunately, the term still isn't validating:

`Provided term is not child of [http://www.ebi.ac.uk/efo/EFO_0002694] at .method.ontology`

Any idea why I'm still seeing this message?

**Comment by paolaroncaglia** [comment]
Hi @rachadele ,
I'll investigate.

**Comment by paolaroncaglia** [comment]
@rachadele 
Please follow this ticket for updates (you should receive email notifications anyway, as you're mentioned there):
https://github.com/ebi-ait/hca-ebi-dev-team/issues/444#issuecomment-927994916

**Comment by paolaroncaglia** [comment]
Following up on this ticket:
The original request from HCA has been addressed;
HCA validation issues have been addressed by the tech team elsewhere;
The [suggestion to improve the 'single cell isolation'/'isolation of cell population' branch in EFO](https://github.com/EBISPOT/efo/issues/1248#issuecomment-916987799), requiring feedback from multiple other teams, hasn't received any follow-up, so there's probably not enough bandwidth (and the branch as is is not breaking anything);
I'll close now. A new ticket may be opened if/as needed.
