### ISSUE TITLE
Review of deprecated classes in other ontologies (causing errors in EFO 3)

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#257]
Running make on the current (i.e. dated 27/7/2018) version of EFO 3 returns error corresponding to a few deprecated classes in other ontologies and to (more numerous) dangling classes. Here we'll review the deprecated ones and assess if tickets should be opened with other ontologies, esp. MONDO.

**Comment by paolaroncaglia** [comment]
At a very quick glance, all 4 'deprecated' errors seem to refer to a single MONDO class. I'll take a look at it and check the very latest version of MONDO (I think they had a release the night before yesterday). Here are the 4 errors:

1)
2018-09-27 16:21:30,141 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=SubClassOf(Annotation(<http://www.geneontology.org/formats/oboInOwl#source> "linkedlifedata"^^xsd:string) <http://www.orpha.net/ORDO/Orphanet_1435> <http://purl.obolibrary.org/obo/MONDO_0004589>), referencedObject=<http://purl.obolibrary.org/obo/MONDO_0004589>, category=DEPRECATED]

2) 2018-09-27 16:21:30,141 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=SubClassOf(Annotation(<http://www.geneontology.org/formats/oboInOwl#source> "linkedlifedata"^^xsd:string) <http://www.orpha.net/ORDO/Orphanet_75858> <http://purl.obolibrary.org/obo/MONDO_0004589>), referencedObject=<http://purl.obolibrary.org/obo/MONDO_0004589>, category=DEPRECATED]

3) 2018-09-27 16:21:30,142 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=SubClassOf(Annotation(<http://www.geneontology.org/formats/oboInOwl#source> "DOID:0090114"^^xsd:string) Annotation(<http://www.geneontology.org/formats/oboInOwl#source> "linkedlifedata/inferred"^^xsd:string) <http://www.orpha.net/ORDO/Orphanet_59181> <http://purl.obolibrary.org/obo/MONDO_0004589>), referencedObject=<http://purl.obolibrary.org/obo/MONDO_0004589>, category=DEPRECATED]

4) 2018-09-27 16:21:30,142 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=SubClassOf(Annotation(<http://www.geneontology.org/formats/oboInOwl#source> "linkedlifedata"^^xsd:string) <http://www.orpha.net/ORDO/Orphanet_1871> <http://purl.obolibrary.org/obo/MONDO_0004589>), referencedObject=<http://purl.obolibrary.org/obo/MONDO_0004589>, category=DEPRECATED]

**Comment by zoependlington** [comment]
I submitted a ticket to MONDO regarding this term last week (https://github.com/monarch-initiative/mondo/issues/344), that they looked into and solved. So, hopefully, it should be resolved in the recent MONDO release.

**Comment by paolaroncaglia** [comment]
@zoependlington 
Thanks for catching that so quickly. That's a bit odd though: Nicole fixed that in MONDO 9 days ago, i.e. on Sept 19th, (commit message says "removed superclasses for obsoleted term") but the new version of MONDO dated Sept 26th still shows that the term has children:
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0004589
I'm afraid that Nicole forgot to remove the children, I'll re-open the MONDO ticket.

**Comment by paolaroncaglia** [comment]
The MONDO ticket has been closed. Next time we build EFO 3, there should be no more errors from deprecated classes. Keeping this ticket open until we verify.
